{{- if .Values.clientInfo.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clientInfo.secretName }}
  namespace: {{ include "flexa-csi.namespace" . }}
  labels:
    {{- include "flexa-csi.labels" . | nindent 4 }}
type: Opaque
stringData:
  client-info.yml: |
{{ .Values.clientInfo.content | nindent 4 }}
{{- end }}
