apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: flexa-sc-lustre
provisioner: csi.flexa.com
parameters:
  proxyProfile: "lustre"
  fs: "lustre"
  clusterName: "cvol"
  protocol: "nfs"
reclaimPolicy: Delete
allowVolumeExpansion: true
